@startuml

package gomoku
{
    enum TableCell {
        EMPTY
        AI
        PLAYER
    }

    class GameLoop {
        public:
        private:
            std::vector<std::vector<TableCell>> map
            AI ai
    }

    class AI {
        public:
            std::string play_ai_turn(const std::vector<std::vector<TableCell>> &)
        private:
    }

    TableCell --> GameLoop
    TableCell --> AI
    AI --> GameLoop
}

@enduml
